# Generated by Django 5.1 on 2024-08-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['first_name'], name='tracking_pe_first_n_d96912_idx'), models.Index(fields=['last_name'], name='tracking_pe_last_na_cffa02_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.people')),
            ],
            options={
                'indexes': [models.Index(fields=['datetime'], name='tracking_lo_datetim_cfdfaa_idx'), models.Index(fields=['people'], name='tracking_lo_people__f63248_idx'), models.Index(fields=['latitude', 'longitude'], name='tracking_lo_latitud_a58d17_idx')],
            },
        ),
    ]
